defmodule Up.Repo.Migrations.AddProductsAndStories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :hash, :text, null: false
      add :state, :text, null: false, default: "initialized"
    end
  end

  def down do
    drop table(:stories)
  end
end
