defmodule Up.Repo.Migrations.AddCoupleImageUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stories) do
      add :couple_image_url, :text
    end
  end

  def down do
    alter table(:stories) do
      remove :couple_image_url
    end
  end
end
