defmodule Up.Repo.Migrations.StorePrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:"stories.frames") do
      add :prompt, :text
    end
  end

  def down do
    alter table(:"stories.frames") do
      remove :prompt
    end
  end
end
